### ISSUE TITLE
Button not working on Giving page

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/ChurchAppsSupport#66]
When you click export on this page nothing happens a full report to CSV would be great. 

![2222](https://user-images.githubusercontent.com/65249159/213757094-f139d82f-7009-45a8-93f0-36e8b95dd813.jpg)

**Comment by jzongker** [comment]
Resolved by https://github.com/LiveChurchSolutions/AppBase/commit/2b04a14dc773adf29742e43ba72df503bd780c32

**Comment by mbyrdLCS** [comment]
it looks Like there was a print button that was added which is good but the download still does not work. 

Also below this window is the same problem 

<img width="1044" alt="Screen Shot 2023-02-02 at 7 49 35 AM" src="https://user-images.githubusercontent.com/65249159/216340149-2e079558-d72d-40c2-85ce-10f1cbd1c97c.png">

**Comment by hamzasiddiqi2168** [comment]
after take pull of main branch in appBase.its working fine . @jzongker  please check it
https://www.loom.com/share/fb5f624f4bdf4393988f8c506bf98ca4
